### ISSUE TITLE
登录不成功

### ISSUE THREAD

**Issue by zw963** [logbird/360yunpan#7]
下面是错误输出.

```py
Logining!
getToken Success
Traceback (most recent call last):
  File "./cli.py", line 107, in <module>
    conf = runCommand(conf, username, password)
  File "./cli.py", line 92, in runCommand
    loginObj, user = login(user, pwd)
  File "./cli.py", line 68, in login
    userinfo = login.run(user, pwd)
  File "/home/zw963/Git/360yunpan/loginYunPan.py", line 167, in run
    userinfo = self.doLogin(username, password, token);
  File "/home/zw963/Git/360yunpan/loginYunPan.py", line 122, in doLogin
    if int(result['errno']) == 0:
ValueError: invalid literal for int() with base 10: 'login_captcha_001'
```

**Comment by logbird** [comment]
是不是账号异地登录了。。这个是有验证码了




发自网易邮箱大师
在2016年11月23日 14:30，Billy.Zheng 写道:

下面是错误输出.

Logining!
getToken Success
Traceback (most recent call last):
  File "./cli.py", line 107, in<module>
    conf = runCommand(conf, username, password)
  File "./cli.py", line 92, in runCommand
    loginObj, user = login(user, pwd)
  File "./cli.py", line 68, in login
    userinfo = login.run(user, pwd)
  File "/home/zw963/Git/360yunpan/loginYunPan.py", line 167, in run
    userinfo =self.doLogin(username, password, token);
  File "/home/zw963/Git/360yunpan/loginYunPan.py", line 122, in doLogin
    ifint(result['errno']) ==0:
ValueError: invalid literal forint() with base 10: 'login_captcha_001'

**Comment by zw963** [comment]
成功了, 谢谢.

**Comment by zw963** [comment]
请问我是不是搞错了, 我其实是希望下载 360 上的文件到本地, 这个工具不适用喽?

**Comment by logbird** [comment]
看一下maip.py里面有这个用法。可以自动下载的


发自网易邮箱大师
在2016年11月25日 14:02，Billy.Zheng 写道:

请问我是不是搞错了, 我其实是希望下载 360 上的文件到本地, 这个工具不适用喽?

**Comment by zw963** [comment]
下载速度好快, 谢谢.

不过不支持中文目录名有点不爽啊, 还得首先把目录改名才可以下载.

**Comment by zw963** [comment]
错误提示:

Get Dir List Error, Please try again later! Message: 系统不可用
